In [10]:
import numpy as np
import pandas as pd
import requests

In [11]:
products_url =  "https://dummyjson.com/products?limit=0"

In [12]:
products_response = requests.get(products_url)

if products_response.status_code == 200:
    products_data = products_response.json()
else:
    print("Products API failed:", products_response.status_code)

In [13]:
products = products_data["products"]

In [14]:
df = pd.DataFrame(products)

In [15]:
df.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22.99}",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.67}",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20.59}",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,"{'width': 18.11, 'height': 28.38, 'depth': 22.17}",3 year warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,"{'width': 21.63, 'height': 16.48, 'depth': 29.84}",1 month warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    194 non-null    int64
 1   title                 194 non-null    str
 2   description           194 non-null    str
 3   category              194 non-null    str
 4   price                 194 non-null    float64
 5   discountPercentage    194 non-null    float64
 6   rating                194 non-null    float64
 7   stock                 194 non-null    int64
 8   tags                  194 non-null    object
 9   brand                 102 non-null    str
 10  sku                   194 non-null    str
 11  weight                194 non-null    int64
 12  dimensions            194 non-null    object
 13  warrantyInformation   194 non-null    str
 14  shippingInformation   194 non-null    str
 15  availabilityStatus    194 non-null    str
 16  reviews               194 non-null    object
 17  returnPolicy          194 non-null    str
 18  minimumOrderQuantity  194 non-null    int64
 19  meta                  194 non-null    object
 20  images                194 non-null    object
 21  thumbnail             194 non-null    str
dtypes: float64(3), int64(4), object(5), str(10)
memory usage: 33.5+ KB

In [17]:
products_data.keys()

dict_keys(['products', 'total', 'skip', 'limit'])

In [18]:
type(products_data)

dict

In [19]:
type(products_data["products"])

list

In [20]:
len(products_data['products'])

194

In [21]:
df = pd.DataFrame(products_data['products'])

In [22]:
df.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22.99}",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.67}",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20.59}",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,"{'width': 18.11, 'height': 28.38, 'depth': 22.17}",3 year warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,"{'width': 21.63, 'height': 16.48, 'depth': 29.84}",1 month warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...

In [23]:
df.shape

(194, 22)

In [24]:
df.isnull().sum()

id                       0
title                    0
description              0
category                 0
price                    0
discountPercentage       0
rating                   0
stock                    0
tags                     0
brand                   92
sku                      0
weight                   0
dimensions               0
warrantyInformation      0
shippingInformation      0
availabilityStatus       0
reviews                  0
returnPolicy             0
minimumOrderQuantity     0
meta                     0
images                   0
thumbnail                0
dtype: int64

In [25]:
df.describe()

,id,price,discountPercentage,rating,stock,weight,minimumOrderQuantity
count,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000
mean,97.500000,1570.102887,10.557835,3.795722,50.407216,5.381443,13.298969
std,56.147128,5509.494435,5.529503,0.728989,30.628209,3.009289,14.178116
min,1.000000,0.790000,0.040000,2.510000,0.000000,1.000000,1.000000
25%,49.250000,11.990000,6.335000,3.180000,25.000000,3.000000,3.000000
50%,97.500000,34.990000,10.765000,3.860000,52.000000,5.000000,8.000000
75%,145.750000,249.990000,14.907500,4.417500,79.000000,8.000000,18.750000
max,194.000000,36999.990000,19.610000,4.990000,100.000000,10.000000,50.000000

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    194 non-null    int64
 1   title                 194 non-null    str
 2   description           194 non-null    str
 3   category              194 non-null    str
 4   price                 194 non-null    float64
 5   discountPercentage    194 non-null    float64
 6   rating                194 non-null    float64
 7   stock                 194 non-null    int64
 8   tags                  194 non-null    object
 9   brand                 102 non-null    str
 10  sku                   194 non-null    str
 11  weight                194 non-null    int64
 12  dimensions            194 non-null    object
 13  warrantyInformation   194 non-null    str
 14  shippingInformation   194 non-null    str
 15  availabilityStatus    194 non-null    str
 16  reviews               194 non-null    object
 17  returnPolicy          194 non-null    str
 18  minimumOrderQuantity  194 non-null    int64
 19  meta                  194 non-null    object
 20  images                194 non-null    object
 21  thumbnail             194 non-null    str
dtypes: float64(3), int64(4), object(5), str(10)
memory usage: 33.5+ KB

In [27]:
df['reviews'][18]

[{'rating': 5,
  'comment': 'Great product!',
  'date': '2025-04-30T09:41:02.053Z',
  'reviewerName': 'Mateo Bennett',
  'reviewerEmail': 'mateo.bennett@x.dummyjson.com'},
 {'rating': 4,
  'comment': 'Highly recommended!',
  'date': '2025-04-30T09:41:02.053Z',
  'reviewerName': 'Jackson Evans',
  'reviewerEmail': 'jackson.evans@x.dummyjson.com'},
 {'rating': 3,
  'comment': 'Not worth the price!',
  'date': '2025-04-30T09:41:02.053Z',
  'reviewerName': 'Sadie Morales',
  'reviewerEmail': 'sadie.morales@x.dummyjson.com'}]

In [28]:
df.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22.99}",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.67}",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20.59}",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,"{'width': 18.11, 'height': 28.38, 'depth': 22.17}",3 year warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,"{'width': 21.63, 'height': 16.48, 'depth': 29.84}",1 month warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...

In [29]:
review_data = []
for i,row in df.iterrows():
  for review in row['reviews']:
    review['product_id'] = row["id"]
    review_data.append(review)

In [30]:
dim_reviews = pd.DataFrame(review_data)

In [31]:
dim_reviews

,rating,comment,date,reviewerName,reviewerEmail,product_id
0,3,Would not recommend!,2025-04-30T09:41:02.053Z,Eleanor Collins,eleanor.collins@x.dummyjson.com,1
1,4,Very satisfied!,2025-04-30T09:41:02.053Z,Lucas Gordon,lucas.gordon@x.dummyjson.com,1
2,5,Highly impressed!,2025-04-30T09:41:02.053Z,Eleanor Collins,eleanor.collins@x.dummyjson.com,1
3,5,Great product!,2025-04-30T09:41:02.053Z,Savannah Gomez,savannah.gomez@x.dummyjson.com,2
4,4,Awesome product!,2025-04-30T09:41:02.053Z,Christian Perez,christian.perez@x.dummyjson.com,2
...,...,...,...,...,...,...
577,4,Would buy again!,2025-04-30T09:41:02.054Z,Avery Barnes,avery.barnes@x.dummyjson.com,193
578,5,Great product!,2025-04-30T09:41:02.054Z,Evelyn Sanchez,evelyn.sanchez@x.dummyjson.com,193
579,4,Very happy with my purchase!,2025-04-30T09:41:02.054Z,Harper Kelly,harper.kelly@x.dummyjson.com,194
580,5,Highly recommended!,2025-04-30T09:41:02.054Z,Gabriel Bailey,gabriel.bailey@x.dummyjson.com,194
581,5,Fast shipping!,2025-04-30T09:41:02.054Z,Natalie Price,natalie.price@x.dummyjson.com,194

In [32]:
dim_reviews.value_counts()

rating  comment                       date                      reviewerName     reviewerEmail                    product_id
3       Would not recommend!          2025-04-30T09:41:02.053Z  Eleanor Collins  eleanor.collins@x.dummyjson.com  1             1
4       Very satisfied!               2025-04-30T09:41:02.053Z  Lucas Gordon     lucas.gordon@x.dummyjson.com     1             1
5       Highly impressed!             2025-04-30T09:41:02.053Z  Eleanor Collins  eleanor.collins@x.dummyjson.com  1             1
        Great product!                2025-04-30T09:41:02.053Z  Savannah Gomez   savannah.gomez@x.dummyjson.com   2             1
4       Awesome product!              2025-04-30T09:41:02.053Z  Christian Perez  christian.perez@x.dummyjson.com  2             1
                                                                                                                               ..
        Would buy again!              2025-04-30T09:41:02.054Z  Avery Barnes     avery.barnes@x.dummyjson.com     193           1
5       Great product!                2025-04-30T09:41:02.054Z  Evelyn Sanchez   evelyn.sanchez@x.dummyjson.com   193           1
4       Very happy with my purchase!  2025-04-30T09:41:02.054Z  Harper Kelly     harper.kelly@x.dummyjson.com     194           1
5       Highly recommended!           2025-04-30T09:41:02.054Z  Gabriel Bailey   gabriel.bailey@x.dummyjson.com   194           1
        Fast shipping!                2025-04-30T09:41:02.054Z  Natalie Price    natalie.price@x.dummyjson.com    194           1
Name: count, Length: 582, dtype: int64

In [33]:
dimensions_data = []

for _,row in df.iterrows():
  row['dimensions']['product_id'] = row["id"]
  dimensions_data.append(row['dimensions'])
dimensions_data
dim_dimensions = pd.DataFrame(dimensions_data)

In [34]:
dim_dimensions

     width  height  depth  product_id
0    15.14   13.08  22.99           1
1     9.26   22.47  27.67           2
2    29.27   27.93  20.59           3
3    18.11   28.38  22.17           4
4    21.63   16.48  29.84           5
..     ...     ...    ...         ...
189  24.77   24.66   6.09         190
190  12.50   20.63  25.04         191
191  23.23    7.19  28.95         192
192  18.85   28.59   7.21         193
193  26.10   22.03  21.61         194

[194 rows x 4 columns]

In [35]:
df['meta'][0]

{'createdAt': '2025-04-30T09:41:02.053Z',
 'updatedAt': '2025-04-30T09:41:02.053Z',
 'barcode': '5784719087687',
 'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'}

In [36]:
meta_data = []

for _,row in df.iterrows():
  row["meta"]['product_id'] = row["id"]
  meta_data.append(row["meta"])  
  
dim_meta = pd.DataFrame(meta_data)

In [37]:
dim_meta

,createdAt,updatedAt,barcode,qrCode,product_id
0,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5784719087687,https://cdn.dummyjson.com/public/qr-code.png,1
1,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9170275171413,https://cdn.dummyjson.com/public/qr-code.png,2
2,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,8418883906837,https://cdn.dummyjson.com/public/qr-code.png,3
3,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9467746727219,https://cdn.dummyjson.com/public/qr-code.png,4
4,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,4063010628104,https://cdn.dummyjson.com/public/qr-code.png,5
...,...,...,...,...,...
189,2025-04-30T09:41:02.054Z,2025-04-30T09:41:02.054Z,7438522857639,https://cdn.dummyjson.com/public/qr-code.png,190
190,2025-04-30T09:41:02.054Z,2025-04-30T09:41:02.054Z,4608359670564,https://cdn.dummyjson.com/public/qr-code.png,191
191,2025-04-30T09:41:02.054Z,2025-04-30T09:41:02.054Z,1265605585958,https://cdn.dummyjson.com/public/qr-code.png,192
192,2025-04-30T09:41:02.054Z,2025-04-30T09:41:02.054Z,8333241081413,https://cdn.dummyjson.com/public/qr-code.png,193
193,2025-04-30T09:41:02.054Z,2025-04-30T09:41:02.054Z,2093537854573,https://cdn.dummyjson.com/public/qr-code.png,194

In [38]:
df['images'][5]

['https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp',
 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp',
 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp']

In [39]:
images_data = []

for _,row in df.iterrows():
  for image in row['images']:
    images_data.append({"product_id":row["id"],"image":image})
dim_images = pd.DataFrame(images_data)

In [40]:
dim_images

     product_id                                              image
0             1  https://cdn.dummyjson.com/product-images/beaut...
1             2  https://cdn.dummyjson.com/product-images/beaut...
2             3  https://cdn.dummyjson.com/product-images/beaut...
3             4  https://cdn.dummyjson.com/product-images/beaut...
4             5  https://cdn.dummyjson.com/product-images/beaut...
..          ...                                                ...
469         193  https://cdn.dummyjson.com/product-images/women...
470         193  https://cdn.dummyjson.com/product-images/women...
471         194  https://cdn.dummyjson.com/product-images/women...
472         194  https://cdn.dummyjson.com/product-images/women...
473         194  https://cdn.dummyjson.com/product-images/women...

[474 rows x 2 columns]

In [41]:
tags_data = []

for _,row in df.iterrows():
  for tag in row['tags']:
    tags_data.append({'product_id':row["id"] ,"tag":tag})
dim_tags = pd.DataFrame(tags_data)

In [42]:
dim_tags

     product_id              tag
0             1           beauty
1             1          mascara
2             2           beauty
3             2        eyeshadow
4             3           beauty
..          ...              ...
359         192  women's watches
360         193          watches
361         193  women's watches
362         194          watches
363         194  women's watches

[364 rows x 2 columns]

In [43]:
df[['brand','description']]

              brand                                        description
0           Essence  The Essence Mascara Lash Princess is a popular...
1    Glamour Beauty  The Eyeshadow Palette with Mirror offers a ver...
2      Velvet Touch  The Powder Canister is a finely milled setting...
3    Chic Cosmetics  The Red Lipstick is a classic and bold choice ...
4      Nail Couture  The Red Nail Polish offers a rich and glossy r...
..              ...                                                ...
189             IWC  The IWC Ingenieur Automatic Steel watch is a d...
190           Rolex  The Rolex Cellini Moonphase watch is a masterp...
191           Rolex  The Rolex Datejust Women's watch is an iconic ...
192    Fashion Gold  The Gold Women's Watch is a stunning accessory...
193     Fashion Co.  The Women's Wrist Watch is a versatile and fas...

[194 rows x 2 columns]

In [44]:
df.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22....",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.6...",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20....",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,"{'width': 18.11, 'height': 28.38, 'depth': 22....",3 year warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,"{'width': 21.63, 'height': 16.48, 'depth': 29....",1 month warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...

In [45]:
df = df.drop(columns = ['tags','dimensions','reviews','meta','images'])

In [46]:
df.head()

,id,title,description,category,price,discountPercentage,rating,stock,brand,sku,weight,warrantyInformation,shippingInformation,availabilityStatus,returnPolicy,minimumOrderQuantity,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,Essence,BEA-ESS-ESS-001,4,1 week warranty,Ships in 3-5 business days,In Stock,No return policy,48,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,Glamour Beauty,BEA-GLA-EYE-002,9,1 year warranty,Ships in 2 weeks,In Stock,7 days return policy,20,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,Velvet Touch,BEA-VEL-POW-003,8,3 months warranty,Ships in 1-2 business days,In Stock,No return policy,22,https://cdn.dummyjson.com/product-images/beaut...
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,Chic Cosmetics,BEA-CHI-LIP-004,1,3 year warranty,Ships in 1 week,In Stock,7 days return policy,40,https://cdn.dummyjson.com/product-images/beaut...
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,Nail Couture,BEA-NAI-NAI-005,8,1 month warranty,Ships overnight,In Stock,No return policy,22,https://cdn.dummyjson.com/product-images/beaut...

In [47]:
users_url = "https://dummyjson.com/users?limit=0"

In [48]:

users_response = requests.get(users_url)

if users_response.status_code == 200:
    users_data = users_response.json()
else:
    print("Users API failed:", users_response.status_code)

In [49]:
user_df = pd.DataFrame(users_data['users'])

In [50]:
user_df.head()

,id,firstName,lastName,maidenName,age,gender,email,phone,username,password,...,address,macAddress,university,bank,company,ein,ssn,userAgent,crypto,role
0,1,Emily,Johnson,Smith,29,female,emily.johnson@x.dummyjson.com,+81 965-431-3024,emilys,emilyspass,...,"{'address': '626 Main Street', 'city': 'Phoeni...",47:fa:41:18:ec:eb,University of Wisconsin--Madison,"{'cardExpire': '05/28', 'cardNumber': '3693233...","{'department': 'Engineering', 'name': 'Dooley,...",977-175,900-590-289,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
1,2,Michael,Williams,,36,male,michael.williams@x.dummyjson.com,+49 258-627-6644,michaelw,michaelwpass,...,"{'address': '385 Fifth Street', 'city': 'Houst...",79:15:78:99:60:aa,Ohio State University,"{'cardExpire': '01/30', 'cardNumber': '3530633...","{'department': 'Support', 'name': 'Spinka - Di...",912-602,108-953-962,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
2,3,Sophia,Brown,,43,female,sophia.brown@x.dummyjson.com,+81 210-652-2785,sophiab,sophiabpass,...,"{'address': '1642 Ninth Street', 'city': 'Wash...",12:a3:d3:6f:5c:5b,Pepperdine University,"{'cardExpire': '10/27', 'cardNumber': '6011212...","{'department': 'Research and Development', 'na...",963-113,638-461-822,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
3,4,James,Davis,,46,male,james.davis@x.dummyjson.com,+49 614-958-9364,jamesd,jamesdpass,...,"{'address': '238 Jefferson Street', 'city': 'S...",10:7d:df:1f:97:58,University of Southern California,"{'cardExpire': '07/30', 'cardNumber': '5303440...","{'department': 'Support', 'name': 'Pagac and S...",904-810,116-951-314,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
4,5,Emma,Miller,Johnson,31,female,emma.miller@x.dummyjson.com,+91 759-776-1614,emmaj,emmajpass,...,"{'address': '607 Fourth Street', 'city': 'Jack...",32:b9:7e:8d:f5:e8,Northeastern University,"{'cardExpire': '07/30', 'cardNumber': '5237188...","{'department': 'Human Resources', 'name': 'Gra...",403-505,526-210-885,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:9...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin

In [51]:
user_df.shape

(208, 28)

In [52]:
user_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 28 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          208 non-null    int64
 1   firstName   208 non-null    str
 2   lastName    208 non-null    str
 3   maidenName  208 non-null    str
 4   age         208 non-null    int64
 5   gender      208 non-null    str
 6   email       208 non-null    str
 7   phone       208 non-null    str
 8   username    208 non-null    str
 9   password    208 non-null    str
 10  birthDate   208 non-null    str
 11  image       208 non-null    str
 12  bloodGroup  208 non-null    str
 13  height      208 non-null    float64
 14  weight      208 non-null    float64
 15  eyeColor    208 non-null    str
 16  hair        208 non-null    object
 17  ip          208 non-null    str
 18  address     208 non-null    object
 19  macAddress  208 non-null    str
 20  university  208 non-null    str
 21  bank        208 non-null    object
 22  company     208 non-null    object
 23  ein         208 non-null    str
 24  ssn         208 non-null    str
 25  userAgent   208 non-null    str
 26  crypto      208 non-null    object
 27  role        208 non-null    str
dtypes: float64(2), int64(2), object(5), str(19)
memory usage: 45.6+ KB

In [53]:
user_df.iloc[0]

id                                                            1
firstName                                                 Emily
lastName                                                Johnson
maidenName                                                Smith
age                                                          29
gender                                                   female
email                             emily.johnson@x.dummyjson.com
phone                                          +81 965-431-3024
username                                                 emilys
password                                             emilyspass
birthDate                                             1996-5-30
image                     https://dummyjson.com/icon/emilys/128
bloodGroup                                                   O-
height                                                   193.24
weight                                                    63.16
eyeColor                                                  Green
hair                        {'color': 'Brown', 'type': 'Curly'}
ip                                                 42.48.100.32
address       {'address': '626 Main Street', 'city': 'Phoeni...
macAddress                                    47:fa:41:18:ec:eb
university                     University of Wisconsin--Madison
bank          {'cardExpire': '05/28', 'cardNumber': '3693233...
company       {'department': 'Engineering', 'name': 'Dooley,...
ein                                                     977-175
ssn                                                 900-590-289
userAgent     Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...
crypto        {'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...
role                                                      admin
Name: 0, dtype: object

In [54]:
user_df.columns

Index(['id', 'firstName', 'lastName', 'maidenName', 'age', 'gender', 'email',
       'phone', 'username', 'password', 'birthDate', 'image', 'bloodGroup',
       'height', 'weight', 'eyeColor', 'hair', 'ip', 'address', 'macAddress',
       'university', 'bank', 'company', 'ein', 'ssn', 'userAgent', 'crypto',
       'role'],
      dtype='str')

In [55]:
hair_data = []

for _,row in user_df.iterrows():
  row['hair']['user_id'] = row["id"]
  hair_data.append(row["hair"])

dim_hair = pd.DataFrame(hair_data)

In [56]:
dim_hair

      color      type  user_id
0     Brown     Curly        1
1     Green  Straight        2
2     White      Wavy        3
3    Blonde  Straight        4
4     White  Straight        5
..      ...       ...      ...
203   Black     Curly      204
204     Red     Curly      205
205   Brown  Straight      206
206   Black  Straight      207
207   Green  Straight      208

[208 rows x 3 columns]

In [57]:
address_data = []

for _,row in user_df.iterrows():
  row['address']['user_id'] = row["id"]
  address_data.append(row["address"])

dim_user_address = pd.DataFrame(address_data)

In [58]:
dim_user_address

,address,city,state,stateCode,postalCode,coordinates,country,user_id
0,626 Main Street,Phoenix,Mississippi,MS,29112,"{'lat': -77.16213, 'lng': -92.084824}",United States,1
1,385 Fifth Street,Houston,Alabama,AL,38807,"{'lat': 22.815468, 'lng': 115.608581}",United States,2
2,1642 Ninth Street,Washington,Alabama,AL,32822,"{'lat': 45.289366, 'lng': 46.832664}",United States,3
3,238 Jefferson Street,Seattle,Pennsylvania,PA,68354,"{'lat': 16.782513, 'lng': -139.34723}",United States,4
4,607 Fourth Street,Jacksonville,Colorado,CO,26593,"{'lat': 0.505589, 'lng': -157.43281}",United States,5
...,...,...,...,...,...,...,...,...
203,798 Ninth Street,Jacksonville,Texas,TX,12771,"{'lat': 23.706655, 'lng': -56.346259}",United States,204
204,1221 Washington Street,Los Angeles,South Carolina,SC,78498,"{'lat': 80.449539, 'lng': -142.231527}",United States,205
205,117 Maple Street,San Francisco,Tennessee,TN,40535,"{'lat': 30.069731, 'lng': -118.879243}",United States,206
206,1856 Tenth Street,Seattle,South Dakota,SD,60977,"{'lat': -64.699698, 'lng': -99.677422}",United States,207
207,1890 First Street,Los Angeles,New Hampshire,NH,53772,"{'lat': -89.0775, 'lng': -81.825967}",United States,208

In [59]:
coordinates_data = []

for _, row in dim_user_address.iterrows():
    coordinates_data.append({
        "user_id": row["user_id"],
        "latitude": row["coordinates"]["lat"],
        "longitude": row["coordinates"]["lng"]
    })

dim_user_coordinates = pd.DataFrame(coordinates_data)

dim_user_coordinates

     user_id   latitude   longitude
0          1 -77.162130  -92.084824
1          2  22.815468  115.608581
2          3  45.289366   46.832664
3          4  16.782513 -139.347230
4          5   0.505589 -157.432810
..       ...        ...         ...
203      204  23.706655  -56.346259
204      205  80.449539 -142.231527
205      206  30.069731 -118.879243
206      207 -64.699698  -99.677422
207      208 -89.077500  -81.825967

[208 rows x 3 columns]

In [60]:
dim_user_address = dim_user_address.drop(columns=["coordinates"])

In [61]:
bank_data = []

for _,row in user_df.iterrows():
  row['bank']['user_id'] = row["id"]
  bank_data.append(row["bank"])

dim_bank = pd.DataFrame(bank_data)

In [62]:
dim_bank

,cardExpire,cardNumber,cardType,currency,iban,user_id
0,05/28,3693233511855044,Diners Club International,GBP,GB74MH2UZLR9TRPHYNU8F8,1
1,01/30,3530633803003665,JCB,USD,DE26362283149158045865,2
2,10/27,6011212053392887,Discover,EUR,DE12191213468288004835,3
3,07/30,5303440212268149,Mastercard,CAD,DE01300746880579852937,4
4,07/30,5237188057591130,Mastercard,NZD,DE19182355652037133559,5
...,...,...,...,...,...,...
203,03/30,6269389588713214,UnionPay,NZD,DE89507404827985024217,204
204,01/29,4922036660101826,Visa,NZD,DE91641615994664908034,205
205,01/30,5437614839810348,Mastercard,INR,DE24112202737130790320,206
206,05/30,6011114091979826,Discover,CNY,DE08456467042398880704,207
207,04/27,4729390503046994,Visa,CAD,DE61932146076474116124,208

In [63]:
company_data = []

for _,row in user_df.iterrows():
  row['company']['user_id'] = row["id"]
  company_data.append(row["company"])

dim_company= pd.DataFrame(company_data)

In [64]:
dim_company

,department,name,title,address,user_id
0,Engineering,"Dooley, Kozey and Cronin",Sales Manager,"{'address': '263 Tenth Street', 'city': 'San F...",1
1,Support,Spinka - Dickinson,Support Specialist,"{'address': '395 Main Street', 'city': 'Los An...",2
2,Research and Development,Schiller - Zieme,Accountant,"{'address': '1896 Washington Street', 'city': ...",3
3,Support,Pagac and Sons,Research Analyst,"{'address': '1622 Lincoln Street', 'city': 'Fo...",4
4,Human Resources,Graham - Gulgowski,Quality Assurance Engineer,"{'address': '1460 Sixth Street', 'city': 'San ...",5
...,...,...,...,...,...
203,Engineering,"Hickle, Altenwerth and Stamm",Software Engineer,"{'address': '1326 Second Street', 'city': 'Den...",204
204,Legal,Moore Inc,Web Developer,"{'address': '240 Third Street', 'city': 'San F...",205
205,Engineering,Heller LLC,Project Manager,"{'address': '139 Jefferson Street', 'city': 'S...",206
206,Marketing,"Quigley, Dare and Kovacek",Data Scientist,"{'address': '574 Madison Street', 'city': 'San...",207
207,Business Development,Schowalter Group,Project Manager,"{'address': '1046 Main Street', 'city': 'San D...",208

In [65]:
user_company_address_data = []

for _,row in dim_company.iterrows():
  row['address']['user_id'] = row["user_id"]
  user_company_address_data.append(row["address"])

dim_user_company_address = pd.DataFrame(user_company_address_data)

dim_user_company_address

,address,city,state,stateCode,postalCode,coordinates,country,user_id
0,263 Tenth Street,San Francisco,Wisconsin,WI,37657,"{'lat': 71.814525, 'lng': -161.150263}",United States,1
1,395 Main Street,Los Angeles,New Hampshire,NH,73442,"{'lat': 79.098326, 'lng': -119.624845}",United States,2
2,1896 Washington Street,Dallas,Nevada,NV,88511,"{'lat': 20.086743, 'lng': -34.577107}",United States,3
3,1622 Lincoln Street,Fort Worth,Pennsylvania,PA,27768,"{'lat': 54.91193, 'lng': -79.498328}",United States,4
4,1460 Sixth Street,San Antonio,Idaho,ID,21965,"{'lat': 44.346545, 'lng': -26.944701}",United States,5
...,...,...,...,...,...,...,...,...
203,1326 Second Street,Denver,Arizona,AZ,10591,"{'lat': 18.569908, 'lng': -50.33752}",United States,204
204,240 Third Street,San Francisco,Minnesota,MN,58649,"{'lat': 3.609112, 'lng': -35.397672}",United States,205
205,139 Jefferson Street,San Antonio,Idaho,ID,50546,"{'lat': 1.356153, 'lng': 175.897893}",United States,206
206,574 Madison Street,San Francisco,Arizona,AZ,19079,"{'lat': 2.230209, 'lng': 84.27201}",United States,207
207,1046 Main Street,San Diego,Massachusetts,MA,75183,"{'lat': -43.398744, 'lng': -176.705236}",United States,208

In [66]:
user_company_address_coordinates_data = []

for _, row in dim_user_company_address.iterrows():
    user_company_address_coordinates_data.append({
        "user_id": row["user_id"],
        "latitude": row["coordinates"]["lat"],
        "longitude": row["coordinates"]["lng"]
    })

dim_user_company_coordinates = pd.DataFrame(
    user_company_address_coordinates_data
)

dim_user_company_coordinates

     user_id   latitude   longitude
0          1  71.814525 -161.150263
1          2  79.098326 -119.624845
2          3  20.086743  -34.577107
3          4  54.911930  -79.498328
4          5  44.346545  -26.944701
..       ...        ...         ...
203      204  18.569908  -50.337520
204      205   3.609112  -35.397672
205      206   1.356153  175.897893
206      207   2.230209   84.272010
207      208 -43.398744 -176.705236

[208 rows x 3 columns]

In [67]:
dim_company = dim_company.drop(columns=["address"])

In [68]:
dim_user_company_address = dim_user_company_address.drop(
    columns=["coordinates"]
)

In [69]:
crypto_data = []

for _,row in user_df.iterrows():
  row['crypto']['user_id'] = row["id"]
  crypto_data.append(row["crypto"])

dim_crypto= pd.DataFrame(crypto_data)

dim_crypto

,coin,wallet,network,user_id
0,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20),1
1,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20),2
2,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20),3
3,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20),4
4,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20),5
...,...,...,...,...
203,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20),204
204,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20),205
205,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20),206
206,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20),207
207,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20),208

In [70]:
user_df.head()

,id,firstName,lastName,maidenName,age,gender,email,phone,username,password,...,address,macAddress,university,bank,company,ein,ssn,userAgent,crypto,role
0,1,Emily,Johnson,Smith,29,female,emily.johnson@x.dummyjson.com,+81 965-431-3024,emilys,emilyspass,...,"{'address': '626 Main Street', 'city': 'Phoeni...",47:fa:41:18:ec:eb,University of Wisconsin--Madison,"{'cardExpire': '05/28', 'cardNumber': '3693233...","{'department': 'Engineering', 'name': 'Dooley,...",977-175,900-590-289,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
1,2,Michael,Williams,,36,male,michael.williams@x.dummyjson.com,+49 258-627-6644,michaelw,michaelwpass,...,"{'address': '385 Fifth Street', 'city': 'Houst...",79:15:78:99:60:aa,Ohio State University,"{'cardExpire': '01/30', 'cardNumber': '3530633...","{'department': 'Support', 'name': 'Spinka - Di...",912-602,108-953-962,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
2,3,Sophia,Brown,,43,female,sophia.brown@x.dummyjson.com,+81 210-652-2785,sophiab,sophiabpass,...,"{'address': '1642 Ninth Street', 'city': 'Wash...",12:a3:d3:6f:5c:5b,Pepperdine University,"{'cardExpire': '10/27', 'cardNumber': '6011212...","{'department': 'Research and Development', 'na...",963-113,638-461-822,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
3,4,James,Davis,,46,male,james.davis@x.dummyjson.com,+49 614-958-9364,jamesd,jamesdpass,...,"{'address': '238 Jefferson Street', 'city': 'S...",10:7d:df:1f:97:58,University of Southern California,"{'cardExpire': '07/30', 'cardNumber': '5303440...","{'department': 'Support', 'name': 'Pagac and S...",904-810,116-951-314,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
4,5,Emma,Miller,Johnson,31,female,emma.miller@x.dummyjson.com,+91 759-776-1614,emmaj,emmajpass,...,"{'address': '607 Fourth Street', 'city': 'Jack...",32:b9:7e:8d:f5:e8,Northeastern University,"{'cardExpire': '07/30', 'cardNumber': '5237188...","{'department': 'Human Resources', 'name': 'Gra...",403-505,526-210-885,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:9...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin

In [71]:
user_df.iloc[0]

id                                                            1
firstName                                                 Emily
lastName                                                Johnson
maidenName                                                Smith
age                                                          29
gender                                                   female
email                             emily.johnson@x.dummyjson.com
phone                                          +81 965-431-3024
username                                                 emilys
password                                             emilyspass
birthDate                                             1996-5-30
image                     https://dummyjson.com/icon/emilys/128
bloodGroup                                                   O-
height                                                   193.24
weight                                                    63.16
eyeColor                                                  Green
hair          {'color': 'Brown', 'type': 'Curly', 'user_id': 1}
ip                                                 42.48.100.32
address       {'address': '626 Main Street', 'city': 'Phoeni...
macAddress                                    47:fa:41:18:ec:eb
university                     University of Wisconsin--Madison
bank          {'cardExpire': '05/28', 'cardNumber': '3693233...
company       {'department': 'Engineering', 'name': 'Dooley,...
ein                                                     977-175
ssn                                                 900-590-289
userAgent     Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...
crypto        {'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...
role                                                      admin
Name: 0, dtype: object

In [72]:
user_df= user_df.drop(columns=['address','bank','company','hair','crypto'])

In [73]:
user_df

,id,firstName,lastName,maidenName,age,gender,email,phone,username,password,...,height,weight,eyeColor,ip,macAddress,university,ein,ssn,userAgent,role
0,1,Emily,Johnson,Smith,29,female,emily.johnson@x.dummyjson.com,+81 965-431-3024,emilys,emilyspass,...,193.24,63.16,Green,42.48.100.32,47:fa:41:18:ec:eb,University of Wisconsin--Madison,977-175,900-590-289,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,admin
1,2,Michael,Williams,,36,male,michael.williams@x.dummyjson.com,+49 258-627-6644,michaelw,michaelwpass,...,186.22,76.32,Red,12.13.116.142,79:15:78:99:60:aa,Ohio State University,912-602,108-953-962,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,admin
2,3,Sophia,Brown,,43,female,sophia.brown@x.dummyjson.com,+81 210-652-2785,sophiab,sophiabpass,...,177.72,52.60,Hazel,214.225.51.195,12:a3:d3:6f:5c:5b,Pepperdine University,963-113,638-461-822,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,admin
3,4,James,Davis,,46,male,james.davis@x.dummyjson.com,+49 614-958-9364,jamesd,jamesdpass,...,193.31,62.10,Amber,101.118.131.66,10:7d:df:1f:97:58,University of Southern California,904-810,116-951-314,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,admin
4,5,Emma,Miller,Johnson,31,female,emma.miller@x.dummyjson.com,+91 759-776-1614,emmaj,emmajpass,...,192.80,63.62,Green,224.126.22.183,32:b9:7e:8d:f5:e8,Northeastern University,403-505,526-210-885,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:9...,admin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,204,Mateo,Perez,,46,male,mateo.perez@x.dummyjson.com,+44 704-302-8113,mateop,mateoppass,...,172.33,56.27,Brown,251.91.116.19,fc:6e:67:26:8b:ff,University of Florida,654-396,199-992-447,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,user
204,205,Aubrey,Garcia,Gray,29,female,aubrey.garcia@x.dummyjson.com,+1 470-576-9130,aubreyg,aubreygpass,...,192.28,85.89,Brown,0.163.108.147,fb:ae:f9:15:24:90,Pepperdine University,428-615,344-154-808,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,user
205,206,Elena,Baker,,35,female,elena.baker@x.dummyjson.com,+49 978-346-6960,elenab,elenabpass,...,150.62,95.55,Brown,85.35.8.29,83:75:b2:b6:ca:8b,Tufts University,509-840,640-201-673,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,user
206,207,Jace,Smith,,42,male,jace.smith@x.dummyjson.com,+1 634-923-7779,jaces,jacespass,...,185.55,59.24,Gray,72.202.161.214,5e:fa:19:da:b9:fc,University of Rochester,422-384,862-683-716,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,user
207,208,Samantha,Martinez,Lopez,28,female,samantha.martinez@x.dummyjson.com,+49 493-402-2473,samanthal,samanthalpass,...,164.29,55.48,Hazel,168.48.152.139,64:d:24:41:77:b8,University of Texas--Austin,951-858,408-210-580,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,user

In [74]:
carts_url = 'https://dummyjson.com/carts?limit=0'

In [75]:

carts_response = requests.get(carts_url)
carts_response.raise_for_status()

carts_data = carts_response.json()

In [76]:

carts_data

{'carts': [{'id': 1,
   'products': [{'id': 162,
     'title': 'Blue Frock',
     'price': 29.99,
     'quantity': 4,
     'total': 119.96,
     'discountPercentage': 12.13,
     'discountedTotal': 105.41,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
    {'id': 113,
     'title': 'Generic Motorcycle',
     'price': 3999.99,
     'quantity': 3,
     'total': 11999.97,
     'discountPercentage': 12.1,
     'discountedTotal': 10547.97,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/thumbnail.webp'},
    {'id': 122,
     'title': 'iPhone 6',
     'price': 299.99,
     'quantity': 3,
     'total': 899.97,
     'discountPercentage': 6.69,
     'discountedTotal': 839.76,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp'},
    {'id': 138,
     'title': 'Baseball Ball',
     'price': 8.99,
     'quantity': 2,
     'total': 17.98,
     'discountPercentage': 1.71,
     'discountedTotal': 17.67,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/thumbnail.webp'}],
   'total': 13037.88,
   'discountedTotal': 11510.81,
   'userId': 1,
   'totalProducts': 4,
   'totalQuantity': 12},
  {'id': 2,
   'products': [{'id': 86,
     'title': 'Man Short Sleeve Shirt',
     'price': 19.99,
     'quantity': 5,
     'total': 99.94999999999999,
     'discountPercentage': 6.83,
     'discountedTotal': 93.12,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp'},
    {'id': 104,
     'title': 'Apple iPhone Charger',
     'price': 19.99,
     'quantity': 2,
     'total': 39.98,
     'discountPercentage': 18.52,
     'discountedTotal': 32.58,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp'}],
   'total': 139.93,
   'discountedTotal': 125.7,
   'userId': 2,
   'totalProducts': 2,
   'totalQuantity': 7},
  {'id': 3,
   'products': [{'id': 24,
     'title': 'Fish Steak',
     'price': 14.99,
     'quantity': 1,
     'total': 14.99,
     'discountPercentage': 4.23,
     'discountedTotal': 14.36,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp'},
    {'id': 123,
     'title': 'iPhone 13 Pro',
     'price': 1099.99,
     'quantity': 1,
     'total': 1099.99,
     'discountPercentage': 9.37,
     'discountedTotal': 996.92,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp'},
    {'id': 129,
     'title': 'Realme X',
     'price': 299.99,
     'quantity': 1,
     'total': 299.99,
     'discountPercentage': 6.95,
     'discountedTotal': 279.14,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/realme-x/thumbnail.webp'},
    {'id': 86,
     'title': 'Man Short Sleeve Shirt',
     'price': 19.99,
     'quantity': 5,
     'total': 99.94999999999999,
     'discountPercentage': 6.83,
     'discountedTotal': 93.12,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp'},
    {'id': 8,
     'title': "Dior J'adore",
     'price': 89.99,
     'quantity': 2,
     'total': 179.98,
     'discountPercentage': 14.72,
     'discountedTotal': 153.49,
     'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
    {'id': 157,
     'title': 'Party Glasses',
     'price': 19.99,
     'quantity': 5,
     'total': 99.94999999999999,
     'discountPercentage': 11.22,
     'discountedTotal': 88.74,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/thumbnail.webp'}],
   'total': 1794.85,
   'discountedTotal': 1625.77,
   'userId': 3,
   'totalProducts': 6,
   'totalQuantity': 15},
  {'id': 4,
   'products': [{'id': 92,
     'title': 'Sports Sneakers Off White Red',
     'price': 109.99,
     'quantity': 3,
     'total': 329.96999999999997,
     'discountPercentage': 0.04,
     'discountedTotal': 329.84,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/thumbnail.webp'},
    {'id': 8,
     'title': "Dior J'adore",
     'price': 89.99,
     'quantity': 4,
     'total': 359.96,
     'discountPercentage': 14.72,
     'discountedTotal': 306.97,
     'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"}],
   'total': 689.93,
   'discountedTotal': 636.81,
   'userId': 4,
   'totalProducts': 2,
   'totalQuantity': 7},
  {'id': 5,
   'products': [{'id': 161,
     'title': 'Samsung Galaxy Tab White',
     'price': 349.99,
     'quantity': 4,
     'total': 1399.96,
     'discountPercentage': 18.2,
     'discountedTotal': 1145.17,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp'},
    {'id': 39,
     'title': 'Soft Drinks',
     'price': 1.99,
     'quantity': 4,
     'total': 7.96,
     'discountPercentage': 17.48,
     'discountedTotal': 6.57,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/soft-drinks/thumbnail.webp'},
    {'id': 3,
     'title': 'Powder Canister',
     'price': 14.99,
     'quantity': 4,
     'total': 59.96,
     'discountPercentage': 9.84,
     'discountedTotal': 54.06,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp'}],
   'total': 1467.88,
   'discountedTotal': 1205.8,
   'userId': 5,
   'totalProducts': 3,
   'totalQuantity': 12},
  {'id': 6,
   'products': [{'id': 192,
     'title': 'Rolex Datejust Women',
     'price': 10999.99,
     'quantity': 5,
     'total': 54999.95,
     'discountPercentage': 15.94,
     'discountedTotal': 46232.96,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/womens-watches/rolex-datejust-women/thumbnail.webp'},
    {'id': 130,
     'title': 'Realme XT',
     'price': 349.99,
     'quantity': 1,
     'total': 349.99,
     'discountPercentage': 11.51,
     'discountedTotal': 309.71,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/realme-xt/thumbnail.webp'},
    {'id': 155,
     'title': 'Classic Sun Glasses',
     'price': 24.99,
     'quantity': 4,
     'total': 99.96,
     'discountPercentage': 4.94,
     'discountedTotal': 95.02,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/thumbnail.webp'},
    {'id': 42,
     'title': 'Water',
     'price': 0.99,
     'quantity': 4,
     'total': 3.96,
     'discountPercentage': 14.92,
     'discountedTotal': 3.37,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/water/thumbnail.webp'}],
   'total': 55453.86,
   'discountedTotal': 46641.06,
   'userId': 6,
   'totalProducts': 4,
   'totalQuantity': 14},
  {'id': 7,
   'products': [{'id': 56,
     'title': 'Electric Stove',
     'price': 49.99,
     'quantity': 1,
     'total': 49.99,
     'discountPercentage': 14.04,
     'discountedTotal': 42.97,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp'},
    {'id': 136,
     'title': 'Vivo X21',
     'price': 499.99,
     'quantity': 1,
     'total': 499.99,
     'discountPercentage': 17.41,
     'discountedTotal': 412.94,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/thumbnail.webp'},
    {'id': 9,
     'title': 'Dolce Shine Eau de',
     'price': 69.99,
     'quantity': 2,
     'total': 139.98,
     'discountPercentage': 0.62,
     'discountedTotal': 139.11,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp'},
    {'id': 120,
     'title': 'Vaseline Men Body and Face Lotion',
     'price': 9.99,
     'quantity': 4,
     'total': 39.96,
     'discountPercentage': 13.39,
     'discountedTotal': 34.61,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/skin-care/vaseline-men-body-and-face-lotion/thumbnail.webp'},
    {'id': 56,
     'title': 'Electric Stove',
     'price': 49.99,
     'quantity': 1,
     'total': 49.99,
     'discountPercentage': 14.04,
     'discountedTotal': 42.97,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp'},
    {'id': 90,
     'title': 'Puma Future Rider Trainers',
     'price': 89.99,
     'quantity': 5,
     'total': 449.95,
     'discountPercentage': 4.2,
     'discountedTotal': 431.05,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp'}],
   'total': 1229.86,
   'discountedTotal': 1103.65,
   'userId': 7,
   'totalProducts': 6,
   'totalQuantity': 14},
  {'id': 8,
   'products': [{'id': 18,
     'title': 'Cat Food',
     'price': 8.99,
     'quantity': 2,
     'total': 17.98,
     'discountPercentage': 9.58,
     'discountedTotal': 16.26,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp'},
    {'id': 50,
     'title': 'Black Whisk',
     'price': 9.99,
     'quantity': 3,
     'total': 29.97,
     'discountPercentage': 10.24,
     'discountedTotal': 26.9,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/black-whisk/thumbnail.webp'},
    {'id': 162,
     'title': 'Blue Frock',
     'price': 29.99,
     'quantity': 4,
     'total': 119.96,
     'discountPercentage': 12.13,
     'discountedTotal': 105.41,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
    {'id': 11,
     'title': 'Annibale Colombo Bed',
     'price': 1899.99,
     'quantity': 3,
     'total': 5699.97,
     'discountPercentage': 8.57,
     'discountedTotal': 5211.48,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp'},
    {'id': 108,
     'title': 'iPhone 12 Silicone Case with MagSafe Plum',
     'price': 29.99,
     'quantity': 4,
     'total': 119.96,
     'discountPercentage': 13.85,
     'discountedTotal': 103.35,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'},
    {'id': 106,
     'title': 'Apple Watch Series 4 Gold',
     'price': 349.99,
     'quantity': 1,
     'total': 349.99,
     'discountPercentage': 12.02,
     'discountedTotal': 307.92,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/thumbnail.webp'}],
   'total': 6337.83,
   'discountedTotal': 5771.32,
   'userId': 8,
   'totalProducts': 6,
   'totalQuantity': 17},
  {'id': 9,
   'products': [{'id': 1,
     'title': 'Essence Mascara Lash Princess',
     'price': 9.99,
     'quantity': 3,
     'total': 29.97,
     'discountPercentage': 10.48,
     'discountedTotal': 26.83,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'},
    {'id': 98,
     'title': 'Rolex Submariner Watch',
     'price': 13999.99,
     'quantity': 2,
     'total': 27999.98,
     'discountPercentage': 5.05,
     'discountedTotal': 26585.98,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp'},
    {'id': 132,
     'title': 'Samsung Galaxy S8',
     'price': 499.99,
     'quantity': 3,
     'total': 1499.97,
     'discountPercentage': 19.45,
     'discountedTotal': 1208.23,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/thumbnail.webp'},
    {'id': 90,
     'title': 'Puma Future Rider Trainers',
     'price': 89.99,
     'quantity': 2,
     'total': 179.98,
     'discountPercentage': 4.2,
     'discountedTotal': 172.42,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp'}],
   'total': 29709.9,
   'discountedTotal': 27993.46,
   'userId': 9,
   'totalProducts': 4,
   'totalQuantity': 10},
  {'id': 10,
   'products': [{'id': 41,
     'title': 'Tissue Paper Box',
     'price': 2.49,
     'quantity': 1,
     'total': 2.49,
     'discountPercentage': 13.28,
     'discountedTotal': 2.16,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/tissue-paper-box/thumbnail.webp'},
    {'id': 108,
     'title': 'iPhone 12 Silicone Case with MagSafe Plum',
     'price': 29.99,
     'quantity': 5,
     'total': 149.95,
     'discountPercentage': 13.85,
     'discountedTotal': 129.18,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'}],
   'total': 152.44,
   'discountedTotal': 131.34,
   'userId': 10,
   'totalProducts': 2,
   'totalQuantity': 6},
  {'id': 11,
   'products': [{'id': 115,
     'title': 'MotoGP CI.H1',
     'price': 14999.99,
     'quantity': 4,
     'total': 59999.96,
     'discountPercentage': 6.92,
     'discountedTotal': 55847.96,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/motogp-ci.h1/thumbnail.webp'},
    {'id': 101,
     'title': 'Apple AirPods Max Silver',
     'price': 549.99,
     'quantity': 2,
     'total': 1099.98,
     'discountPercentage': 13.67,
     'discountedTotal': 949.61,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp'},
    {'id': 55,
     'title': 'Egg Slicer',
     'price': 6.99,
     'quantity': 4,
     'total': 27.96,
     'discountPercentage': 14.76,
     'discountedTotal': 23.83,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/egg-slicer/thumbnail.webp'},
    {'id': 25,
     'title': 'Green Bell Pepper',
     'price': 1.29,
     'quantity': 3,
     'total': 3.87,
     'discountPercentage': 0.16,
     'discountedTotal': 3.86,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp'},
    {'id': 161,
     'title': 'Samsung Galaxy Tab White',
     'price': 349.99,
     'quantity': 2,
     'total': 699.98,
     'discountPercentage': 18.2,
     'discountedTotal': 572.58,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp'}],
   'total': 61831.75,
   'discountedTotal': 57397.84,
   'userId': 11,
   'totalProducts': 5,
   'totalQuantity': 15},
  {'id': 12,
   'products': [{'id': 117,
     'title': 'Sportbike Motorcycle',
     'price': 7499.99,
     'quantity': 1,
     'total': 7499.99,
     'discountPercentage': 11.58,
     'discountedTotal': 6631.49,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/sportbike-motorcycle/thumbnail.webp'},
    {'id': 28,
     'title': 'Ice Cream',
     'price': 5.49,
     'quantity': 5,
     'total': 27.450000000000003,
     'discountPercentage': 8.69,
     'discountedTotal': 25.06,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp'},
    {'id': 98,
     'title': 'Rolex Submariner Watch',
     'price': 13999.99,
     'quantity': 2,
     'total': 27999.98,
     'discountPercentage': 5.05,
     'discountedTotal': 26585.98,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp'},
    {'id': 8,
     'title': "Dior J'adore",
     'price': 89.99,
     'quantity': 1,
     'total': 89.99,
     'discountPercentage': 14.72,
     'discountedTotal': 76.74,
     'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
    {'id': 162,
     'title': 'Blue Frock',
     'price': 29.99,
     'quantity': 5,
     'total': 149.95,
     'discountPercentage': 12.13,
     'discountedTotal': 131.76,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
    {'id': 14,
     'title': 'Knoll Saarinen Executive Conference Chair',
     'price': 499.99,
     'quantity': 4,
     'total': 1999.96,
     'discountPercentage': 2.01,
     'discountedTotal': 1959.76,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp'}],
   'total': 37767.32,
   'discountedTotal': 35410.79,
   'userId': 12,
   'totalProducts': 6,
   'totalQuantity': 18},
  {'id': 13,
   'products': [{'id': 35,
     'title': 'Potatoes',
     'price': 2.29,
     'quantity': 2,
     'total': 4.58,
     'discountPercentage': 5.38,
     'discountedTotal': 4.33,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/potatoes/thumbnail.webp'},
    {'id': 23,
     'title': 'Eggs',
     'price': 2.99,
     'quantity': 4,
     'total': 11.96,
     'discountPercentage': 11.05,
     'discountedTotal': 10.64,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp'}],
   'total': 16.54,
   'discountedTotal': 14.97,
   'userId': 13,
   'totalProducts': 2,
   'totalQuantity': 6},
  {'id': 14,
   'products': [{'id': 44,
     'title': 'Family Tree Photo Frame',
     'price': 29.99,
     'quantity': 4,
     'total': 119.96,
     'discountPercentage': 14.87,
     'discountedTotal': 102.12,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/home-decoration/family-tree-photo-frame/thumbnail.webp'},
    {'id': 68,
     'title': 'Pan',
     'price': 24.99,
     'quantity': 1,
     'total': 24.99,
     'discountPercentage': 3,
     'discountedTotal': 24.24,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/pan/thumbnail.webp'},
    {'id': 65,
     'title': 'Lunch Box',
     'price': 12.99,
     'quantity': 5,
     'total': 64.95,
     'discountPercentage': 10.34,
     'discountedTotal': 58.23,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/lunch-box/thumbnail.webp'}],
   'total': 209.9,
   'discountedTotal': 184.59,
   'userId': 14,
   'totalProducts': 3,
   'totalQuantity': 10},
  {'id': 15,
   'products': [{'id': 61,
     'title': 'Hand Blender',
     'price': 34.99,
     'quantity': 2,
     'total': 69.98,
     'discountPercentage': 17.02,
     'discountedTotal': 58.07,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/hand-blender/thumbnail.webp'},
    {'id': 105,
     'title': 'Apple MagSafe Battery Pack',
     'price': 99.99,
     'quantity': 1,
     'total': 99.99,
     'discountPercentage': 17.17,
     'discountedTotal': 82.82,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp'},
    {'id': 141,
     'title': 'Basketball Rim',
     'price': 39.99,
     'quantity': 2,
     'total': 79.98,
     'discountPercentage': 7.74,
     'discountedTotal': 73.79,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/sports-accessories/basketball-rim/thumbnail.webp'}],
   'total': 249.95,
   'discountedTotal': 214.68,
   'userId': 15,
   'totalProducts': 3,
   'totalQuantity': 5},
  {'id': 16,
   'products': [{'id': 20,
     'title': 'Cooking Oil',
     'price': 4.99,
     'quantity': 5,
     'total': 24.950000000000003,
     'discountPercentage': 9.33,
     'discountedTotal': 22.62,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp'},
    {'id': 91,
     'title': 'Sports Sneakers Off White & Red',
     'price': 119.99,
     'quantity': 3,
     'total': 359.96999999999997,
     'discountPercentage': 4.97,
     'discountedTotal': 342.08,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp'}],
   'total': 384.92,
   'discountedTotal': 364.7,
   'userId': 16,
   'totalProducts': 2,
   'totalQuantity': 8},
  {'id': 17,
   'products': [{'id': 123,
     'title': 'iPhone 13 Pro',
     'price': 1099.99,
     'quantity': 5,
     'total': 5499.95,
     'discountPercentage': 9.37,
     'discountedTotal': 4984.6,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp'},
    {'id': 137,
     'title': 'American Football',
     'price': 19.99,

In [77]:
carts_df = pd.DataFrame(carts_data['carts'])

In [78]:
carts_df

,id,products,total,discountedTotal,userId,totalProducts,totalQuantity
0,1,"[{'id': 162, 'title': 'Blue Frock', 'price': 2...",13037.88,11510.81,1,4,12
1,2,"[{'id': 86, 'title': 'Man Short Sleeve Shirt',...",139.93,125.70,2,2,7
2,3,"[{'id': 24, 'title': 'Fish Steak', 'price': 14...",1794.85,1625.77,3,6,15
3,4,"[{'id': 92, 'title': 'Sports Sneakers Off Whit...",689.93,636.81,4,2,7
4,5,"[{'id': 161, 'title': 'Samsung Galaxy Tab Whit...",1467.88,1205.80,5,3,12
...,...,...,...,...,...,...,...
203,204,"[{'id': 141, 'title': 'Basketball Rim', 'price...",25591.84,23182.99,204,6,16
204,205,"[{'id': 62, 'title': 'Ice Cube Tray', 'price':...",16011.94,14075.86,205,2,6
205,206,"[{'id': 141, 'title': 'Basketball Rim', 'price...",229.92,213.26,206,3,8
206,207,"[{'id': 137, 'title': 'American Football', 'pr...",22719.79,20090.11,207,6,21
207,208,"[{'id': 3, 'title': 'Powder Canister', 'price'...",304.95,260.12,208,2,5

In [79]:
carts_df['products'][0]

[{'id': 162,
  'title': 'Blue Frock',
  'price': 29.99,
  'quantity': 4,
  'total': 119.96,
  'discountPercentage': 12.13,
  'discountedTotal': 105.41,
  'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
 {'id': 113,
  'title': 'Generic Motorcycle',
  'price': 3999.99,
  'quantity': 3,
  'total': 11999.97,
  'discountPercentage': 12.1,
  'discountedTotal': 10547.97,
  'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/thumbnail.webp'},
 {'id': 122,
  'title': 'iPhone 6',
  'price': 299.99,
  'quantity': 3,
  'total': 899.97,
  'discountPercentage': 6.69,
  'discountedTotal': 839.76,
  'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp'},
 {'id': 138,
  'title': 'Baseball Ball',
  'price': 8.99,
  'quantity': 2,
  'total': 17.98,
  'discountPercentage': 1.71,
  'discountedTotal': 17.67,
  'thumbnail': 'https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/thumbnail.webp'}]

In [80]:
carts_products_data = []

for _,row in carts_df.iterrows():
  cart_id = row['id']
  for product in row['products']:
    carts_products_data.append({
      "cart_id" : cart_id,
      'product_id': product['id'],
      'title': product['title'],
      'price': product['price'],
      'quantity': product['quantity'],
      'total': product['total'],
      'discountPercentage': product['discountPercentage'],
      'discountedTotal': product['discountedTotal'],
      'thumbnail': product['thumbnail']
    })
    
dim_carts_products = pd.DataFrame(carts_products_data)
dim_carts_products

,cart_id,product_id,title,price,quantity,total,discountPercentage,discountedTotal,thumbnail
0,1,162,Blue Frock,29.99,4,119.96,12.13,105.41,https://cdn.dummyjson.com/product-images/tops/...
1,1,113,Generic Motorcycle,3999.99,3,11999.97,12.10,10547.97,https://cdn.dummyjson.com/product-images/motor...
2,1,122,iPhone 6,299.99,3,899.97,6.69,839.76,https://cdn.dummyjson.com/product-images/smart...
3,1,138,Baseball Ball,8.99,2,17.98,1.71,17.67,https://cdn.dummyjson.com/product-images/sport...
4,2,86,Man Short Sleeve Shirt,19.99,5,99.95,6.83,93.12,https://cdn.dummyjson.com/product-images/mens-...
...,...,...,...,...,...,...,...,...,...
795,207,164,Gray Dress,34.99,4,139.96,14.28,119.97,https://cdn.dummyjson.com/product-images/tops/...
796,207,117,Sportbike Motorcycle,7499.99,3,22499.97,11.58,19894.47,https://cdn.dummyjson.com/product-images/motor...
797,207,16,Apple,1.99,3,5.97,12.62,5.22,https://cdn.dummyjson.com/product-images/groce...
798,208,3,Powder Canister,14.99,3,44.97,9.84,40.54,https://cdn.dummyjson.com/product-images/beaut...
799,208,100,Apple Airpods,129.99,2,259.98,15.54,219.58,https://cdn.dummyjson.com/product-images/mobil...

In [81]:
carts_df = carts_df.drop(columns=['products'])

In [82]:
carts_df

      id     total  discountedTotal  userId  totalProducts  totalQuantity
0      1  13037.88         11510.81       1              4             12
1      2    139.93           125.70       2              2              7
2      3   1794.85          1625.77       3              6             15
3      4    689.93           636.81       4              2              7
4      5   1467.88          1205.80       5              3             12
..   ...       ...              ...     ...            ...            ...
203  204  25591.84         23182.99     204              6             16
204  205  16011.94         14075.86     205              2              6
205  206    229.92           213.26     206              3              8
206  207  22719.79         20090.11     207              6             21
207  208    304.95           260.12     208              2              5

[208 rows x 6 columns]

In [83]:
df.shape

(194, 17)

In [84]:
df.isnull().sum()

id                       0
title                    0
description              0
category                 0
price                    0
discountPercentage       0
rating                   0
stock                    0
brand                   92
sku                      0
weight                   0
warrantyInformation      0
shippingInformation      0
availabilityStatus       0
returnPolicy             0
minimumOrderQuantity     0
thumbnail                0
dtype: int64

In [85]:
df.duplicated().sum()

np.int64(0)

In [86]:
dim_reviews.shape

(582, 6)

In [87]:
dim_reviews.duplicated().sum()

np.int64(0)

In [88]:
dim_dimensions.shape

(194, 4)

In [89]:
dim_dimensions.duplicated().sum()

np.int64(0)

In [90]:
dim_meta.shape

(194, 5)

In [91]:
dim_meta.duplicated().sum()

np.int64(0)

In [92]:
dim_images.shape

(474, 2)

In [93]:
dim_images.duplicated().sum()

np.int64(0)

In [94]:
dim_tags.shape

(364, 2)

In [95]:
dim_tags.duplicated().sum()

np.int64(0)

In [96]:
dim_hair.duplicated().sum()

np.int64(0)

In [97]:
dim_user_address.duplicated().sum()

np.int64(0)

In [98]:
dim_user_company_address.duplicated().sum()

np.int64(0)

In [99]:
dim_crypto.duplicated().sum()

np.int64(0)

In [100]:
dim_user_coordinates.duplicated().sum()

np.int64(0)

In [101]:
carts_df.shape

(208, 6)

In [102]:
carts_df.isnull().sum()

id                 0
total              0
discountedTotal    0
userId             0
totalProducts      0
totalQuantity      0
dtype: int64

In [103]:
carts_df.duplicated().sum()

np.int64(0)

In [104]:
dim_carts_products.shape

(800, 9)

In [105]:
dim_carts_products=dim_carts_products.drop_duplicates()

In [106]:
dim_carts_products.duplicated().sum()

np.int64(0)

In [107]:
dim_bank.duplicated().sum()

np.int64(0)

In [108]:
dim_company.duplicated().sum()

np.int64(0)

In [109]:
dim_user_company_coordinates.duplicated().sum()

np.int64(0)

In [110]:
user_df.duplicated().sum()

np.int64(0)

In [111]:
user_df.isnull().sum()

id            0
firstName     0
lastName      0
maidenName    0
age           0
gender        0
email         0
phone         0
username      0
password      0
birthDate     0
image         0
bloodGroup    0
height        0
weight        0
eyeColor      0
ip            0
macAddress    0
university    0
ein           0
ssn           0
userAgent     0
role          0
dtype: int64

In [112]:
import os

os.makedirs("data", exist_ok=True)

In [113]:
##Products 

df.to_csv("data/products.csv", index=False)

dim_reviews.to_csv("data/product_reviews.csv", index=False)
dim_dimensions.to_csv("data/product_dimensions.csv", index=False)
dim_meta.to_csv("data/product_meta.csv", index=False)
dim_images.to_csv("data/product_images.csv", index=False)
dim_tags.to_csv("data/product_tags.csv", index=False)

In [114]:
##Users

user_df.to_csv("data/users.csv", index=False)

dim_hair.to_csv("data/user_hair.csv", index=False)
dim_user_address.to_csv("data/user_address.csv", index=False)
dim_user_coordinates.to_csv("data/user_coordinates.csv", index=False)
dim_bank.to_csv("data/user_bank.csv", index=False)
dim_company.to_csv("data/user_company.csv", index=False)
dim_user_company_address.to_csv("data/user_company_address.csv", index=False)
dim_user_company_coordinates.to_csv("data/user_company_coordinates.csv", index=False)
dim_crypto.to_csv("data/user_crypto.csv", index=False)

In [115]:
##Carts

carts_df.to_csv("data/carts.csv", index=False)
dim_carts_products.to_csv("data/cart_products.csv", index=False)