In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("data/raw/ecom.csv")

In [3]:
df.head(100)

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating
0,ORD011416,CUST00003,2026-04-03,Books,Self-Help Book,3,9.16,5.0,Net Banking,London,UK,Delivered,5.0
1,ORD000974,CUST00269,10-15-2024,Books,Fiction Novel,1,34.24,5.0,NetBanking,Toronto,CA,Shipped,NaN
2,ORD000617,CUST02075,17 Jun 2024,Home & Kitchen,Vacuum Cleaner,2,111.95,15.0,DEBIT CARD,Brisbane,Australia,Shipped,NaN
3,ORD006437,CUST02109,16/10/2025,Beauty,Hair Dryer,1,31.84,0.0,Cash on Delivery,Birmingham,U.K.,Delivered,3.0
4,ORD000740,CUST00349,06 Apr 2026,Home & Kitchen,Non-Stick Pan,2,72.00,NaN,Credit_Card,Montreal,CA,Delivered,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,ORD003125,CUST00689,2025/10/27,Sports,Yoga Mat,1,33.28,0.0,paypal,Toronto,CA,Cancelled,NaN
96,ORD009586,CUST01322,07/09/2024,Electronics,Gaming Mouse,3,231.52,0.0,PayPal,New York,U.S.A,Pending,NaN
97,ORD004485,CUST02488,08/07/2024,Sports,Football,1,18.47,10.0,net banking,Dubai,UAE,Shipped,NaN
98,ORD001052,CUST03264,2024/08/25,Home & Kitchen,Storage Organizer,1,130.15,0.0,Pay Pal,Hyderabad,India,Delivered,4.0
99,ORD003992,CUST02965,09-20-2025,Books,Fiction Novel,1,12.94,10.0,PayPal,Melbourne,Australia,Shipped,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          12180 non-null  str
 1   Customer_ID       12180 non-null  str
 2   Order_Date        12180 non-null  str
 3   Product_Category  12180 non-null  str
 4   Product_Name      12180 non-null  str
 5   Quantity          12180 non-null  int64
 6   Unit_Price_USD    12180 non-null  float64
 7   Discount_Percent  11445 non-null  float64
 8   Payment_Method    12180 non-null  str
 9   Shipping_City     11678 non-null  str
 10  Country           12180 non-null  str
 11  Order_Status      12180 non-null  str
 12  Customer_Rating   6030 non-null   float64
dtypes: float64(3), int64(1), str(9)
memory usage: 1.2 MB

In [5]:
df['Order_Date'].value_counts().head(20)

Order_Date
09-07-2024     12
25/07/2024     11
04-15-2025     10
19/11/2025      9
03-18-2026      9
16 Oct 2024     9
08 Jun 2026     9
29 Jun 2025     9
2024/04/02      8
2025-01-22      8
2025-07-11      8
2026/04/30      8
2024/12/26      8
12-02-2025      8
19 Feb 2025     8
2025/02/13      8
2026/06/07      8
2025/01/11      8
30 Apr 2026     8
2024-11-17      7
Name: count, dtype: int64

In [6]:
df['create_order_date'] = pd.to_datetime(df['Order_Date'],errors='coerce',format="mixed")

In [7]:
df.head(20)

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating,create_order_date
0,ORD011416,CUST00003,2026-04-03,Books,Self-Help Book,3,9.16,5.0,Net Banking,London,UK,Delivered,5.0,2026-04-03
1,ORD000974,CUST00269,10-15-2024,Books,Fiction Novel,1,34.24,5.0,NetBanking,Toronto,CA,Shipped,NaN,2024-10-15
2,ORD000617,CUST02075,17 Jun 2024,Home & Kitchen,Vacuum Cleaner,2,111.95,15.0,DEBIT CARD,Brisbane,Australia,Shipped,NaN,2024-06-17
3,ORD006437,CUST02109,16/10/2025,Beauty,Hair Dryer,1,31.84,0.0,Cash on Delivery,Birmingham,U.K.,Delivered,3.0,2025-10-16
4,ORD000740,CUST00349,06 Apr 2026,Home & Kitchen,Non-Stick Pan,2,72.00,NaN,Credit_Card,Montreal,CA,Delivered,NaN,2026-04-06
5,ORD011216,CUST02900,11-09-2024,Home & Kitchen,Storage Organizer,1,125.28,0.0,NetBanking,Los Angeles,U.S.A,Delivered,4.0,2024-11-09
6,ORD002861,CUST01324,21/03/2026,Fashion,Formal Shirt,1,18.34,5.0,upi,Brisbane,Australia,Cancelled,NaN,2026-03-21
7,ORD011407,CUST00135,10/07/2024,Books,Cookbook,3,37.49,NaN,Cash on Delivery,New York,USA,Returned,NaN,2024-10-07
8,ORD005427,CUST00945,19/08/2025,Home & Kitchen,Vacuum Cleaner,4,21.44,NaN,NetBanking,Los Angeles,USA,Shipped,NaN,2025-08-19
9,ORD002304,CUST02603,07-14-2025,Sports,Dumbbell Set,1,20.77,10.0,Pay Pal,Munich,germany,Cancelled,NaN,2025-07-14
10,ORD006172,CUST00940,06-05-2024,Books,Kids Storybook,3,37.22,5.0,debit card,Melbourne,Australia,Delivered,NaN,2024-06-05
11,ORD001560,CUST02535,09 Jun 2025,Beauty,Sunscreen SPF50,2,30.41,10.0,paypal,Montreal,CA,Delivered,5.0,2025-06-09
12,ORD006143,CUST01216,11 Jun 2025,Toys,Remote Control Car,2,50.78,0.0,Credit_Card,Manchester,UK,Shipped,NaN,2025-06-11
13,ORD002406,CUST00026,12-09-2024,Toys,Action Figure,1,14.44,0.0,COD,Montreal,canada,Shipped,NaN,2024-12-09
14,ORD008099,CUST00959,12-23-2025,Sports,Cycling Helmet,1,96.33,0.0,CREDIT CARD,Chicago,United States,Delivered,5.0,2025-12-23
15,ORD000325,CUST02081,15 Jul 2025,Electronics,Webcam,1,121.61,0.0,Credit Card,Delhi,IN,Cancelled,NaN,2025-07-15
16,ORD004378,CUST00157,2025/11/05,Books,Kids Storybook,2,9.06,10.0,Debit Card,Houston,usa,Delivered,4.0,2025-11-05
17,ORD006544,CUST01974,11 Nov 2025,Fashion,Cotton T-Shirt,2,27.82,20.0,net banking,Hamburg,DE,Delivered,4.0,2025-11-11
18,ORD011722,CUST00989,04/04/2025,Toys,Building Blocks Set,5,78.21,15.0,cash on delivery,Toronto,CA,Delivered,5.0,2025-04-04
19,ORD011697,CUST02152,04-16-2026,Fashion,Cotton T-Shirt,3,86.68,NaN,Pay Pal,Munich,DE,Shipped,NaN,2026-04-16

In [8]:
df['Discount_Percent'].isna().sum()

np.int64(735)

In [9]:
df['Discount_Percent'].describe()

count    11445.000000
mean         7.299257
std          7.120143
min          0.000000
25%          0.000000
50%          5.000000
75%         10.000000
max         25.000000
Name: Discount_Percent, dtype: float64

In [10]:
## Missing Discount_Percent values were replaced with 0 because 0% is a valid and frequent value in the dataset, and missing discounts are assumed to indicate that no discount was applied.

In [11]:
df["Discount_Percent"] = df["Discount_Percent"].fillna(0)

In [12]:
df['Discount_Percent'].isna().sum()

np.int64(0)

In [13]:
df

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating,create_order_date
0,ORD011416,CUST00003,2026-04-03,Books,Self-Help Book,3,9.16,5.0,Net Banking,London,UK,Delivered,5.0,2026-04-03
1,ORD000974,CUST00269,10-15-2024,Books,Fiction Novel,1,34.24,5.0,NetBanking,Toronto,CA,Shipped,NaN,2024-10-15
2,ORD000617,CUST02075,17 Jun 2024,Home & Kitchen,Vacuum Cleaner,2,111.95,15.0,DEBIT CARD,Brisbane,Australia,Shipped,NaN,2024-06-17
3,ORD006437,CUST02109,16/10/2025,Beauty,Hair Dryer,1,31.84,0.0,Cash on Delivery,Birmingham,U.K.,Delivered,3.0,2025-10-16
4,ORD000740,CUST00349,06 Apr 2026,Home & Kitchen,Non-Stick Pan,2,72.00,0.0,Credit_Card,Montreal,CA,Delivered,NaN,2026-04-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175,ORD002515,CUST00071,2025-10-17,Home & Kitchen,Storage Organizer,1,106.25,0.0,net banking,Chicago,U.S.A,Delivered,4.0,2025-10-17
12176,ORD011799,CUST02583,2024/01/22,Beauty,Sunscreen SPF50,1,24.76,15.0,Pay Pal,Mumbai,india,Delivered,5.0,2024-01-22
12177,ORD006638,CUST02113,02-28-2024,Grocery,Olive Oil 1L,1,29.95,10.0,U.P.I,Melbourne,AU,Pending,NaN,2024-02-28
12178,ORD002576,CUST00298,2025-06-01,Beauty,Hair Dryer,1,41.41,15.0,Credit_Card,Vancouver,CA,Delivered,NaN,2025-06-01
12179,ORD007337,CUST00195,11-18-2024,Books,Self-Help Book,4,27.81,0.0,NetBanking,Mumbai,India,Delivered,4.0,2024-11-18

In [14]:
df['Payment_Method'].info()

<class 'pandas.Series'>
RangeIndex: 12180 entries, 0 to 12179
Series name: Payment_Method
Non-Null Count  Dtype
--------------  -----
12180 non-null  str
dtypes: str(1)
memory usage: 95.3 KB

In [15]:
def correct(x):
  word = ""
  for ch in x:
    if ch not in " .,!@#$%^&*()_-+=":
      word += ch.lower()
      
      if word == "cod":
            return "cash on delivery"
          
      if word in ("net","credit","debit","cash") or word.endswith("on"):
        word += " "
  return word

In [16]:
df['Payment_Method'].apply(correct).unique()

<StringArray>
['net banking', 'debit card', 'cash on delivery', 'credit card', 'upi',
 'paypal']
Length: 6, dtype: str

In [17]:
df['Payment_Method'] = df['Payment_Method'].apply(correct)

In [18]:
df['Country'].unique()

<StringArray>
[            'UK',             'CA',      'Australia',           'U.K.',
          'U.S.A',            'USA',        'germany',         'canada',
  'United States',             'IN',            'usa',             'DE',
             'AU',          'India',            'UAE',          'india',
      'australia',        'Germany',          'U.A.E',            'uae',
             'uk',             'US', 'United Kingdom',         'Canada']
Length: 24, dtype: str

In [19]:
country_map = {
    "UK": "United Kingdom",
    "U.K.": "United Kingdom",
    "uk": "United Kingdom",

    "CA": "Canada",
    "canada": "Canada",
    "Canada": "Canada",

    "Australia": "Australia",
    "AU": "Australia",
    "australia": "Australia",

    "U.S.A": "United States",
    "USA": "United States",
    "usa": "United States",
    "US": "United States",
    "United States": "United States",

    "IN": "India",
    "India": "India",
    "india": "India",

    "DE": "Germany",
    "germany": "Germany",
    "Germany": "Germany",

    "UAE": "United Arab Emirates",
    "U.A.E": "United Arab Emirates",
    "uae": "United Arab Emirates"
}

In [20]:
df['Country'] = df['Country'].map(country_map)

In [21]:
df[df['Country'].isna()]

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating,create_order_date
82,ORD011729,CUST01005,2026/06/25,Electronics,Webcam,4,132.11,20.0,paypal,Birmingham,NaN,Delivered,4.0,2026-06-25
111,ORD004392,CUST03106,03-21-2024,Grocery,Almonds 500g,3,15.70,10.0,net banking,Birmingham,NaN,Delivered,5.0,2024-03-21
125,ORD000750,CUST02531,2025/11/13,Toys,Remote Control Car,4,31.60,0.0,cash on delivery,Manchester,NaN,Shipped,NaN,2025-11-13
199,ORD011075,CUST00508,16 Jul 2024,Home & Kitchen,Blender,2,171.90,10.0,cash on delivery,Birmingham,NaN,Delivered,3.0,2024-07-16
286,ORD004668,CUST02984,2025-08-04,Books,Cookbook,1,37.07,0.0,paypal,London,NaN,Cancelled,NaN,2025-08-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,ORD008417,CUST00361,11/09/2024,Toys,Remote Control Car,1,37.03,5.0,net banking,Manchester,NaN,Delivered,4.0,2024-11-09
12055,ORD006792,CUST00496,03/05/2026,Toys,Building Blocks Set,1,33.37,10.0,debit card,London,NaN,Delivered,5.0,2026-03-05
12101,ORD004421,CUST00923,18/06/2025,Home & Kitchen,Vacuum Cleaner,1,109.23,0.0,cash on delivery,Birmingham,NaN,Delivered,3.0,2025-06-18
12151,ORD000256,CUST02659,05 Mar 2026,Toys,Action Figure,1,78.56,0.0,credit card,London,NaN,Pending,NaN,2026-03-05
12153,ORD003643,CUST00707,24/05/2025,Sports,Yoga Mat,1,44.87,0.0,cash on delivery,Manchester,NaN,Delivered,2.0,2025-05-24

In [22]:
df['Shipping_City'].unique()

<StringArray>
[     'London',     'Toronto',    'Brisbane',  'Birmingham',    'Montreal',
 'Los Angeles',    'New York',      'Munich',   'Melbourne',  'Manchester',
     'Chicago',       'Delhi',     'Houston',     'Hamburg',      'Mumbai',
       'Dubai',      'Berlin',   'Bengaluru',   'Abu Dhabi',      'Sydney',
           nan,   'Vancouver',   'Hyderabad']
Length: 23, dtype: str

In [23]:
city_country = {
    "London": "United Kingdom",
    "Birmingham": "United Kingdom",
    "Manchester": "United Kingdom",

    "Toronto": "Canada",
    "Montreal": "Canada",
    "Vancouver": "Canada",

    "Brisbane": "Australia",
    "Melbourne": "Australia",
    "Sydney": "Australia",

    "Los Angeles": "United States",
    "New York": "United States",
    "Chicago": "United States",
    "Houston": "United States",

    "Munich": "Germany",
    "Hamburg": "Germany",
    "Berlin": "Germany",

    "Delhi": "India",
    "Mumbai": "India",
    "Bengaluru": "India",
    "Hyderabad": "India",

    "Dubai": "United Arab Emirates",
    "Abu Dhabi": "United Arab Emirates"
}

In [24]:
df['Country']= df['Country'].fillna(df['Shipping_City'].map(city_country))

In [25]:
df

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating,create_order_date
0,ORD011416,CUST00003,2026-04-03,Books,Self-Help Book,3,9.16,5.0,net banking,London,United Kingdom,Delivered,5.0,2026-04-03
1,ORD000974,CUST00269,10-15-2024,Books,Fiction Novel,1,34.24,5.0,net banking,Toronto,Canada,Shipped,NaN,2024-10-15
2,ORD000617,CUST02075,17 Jun 2024,Home & Kitchen,Vacuum Cleaner,2,111.95,15.0,debit card,Brisbane,Australia,Shipped,NaN,2024-06-17
3,ORD006437,CUST02109,16/10/2025,Beauty,Hair Dryer,1,31.84,0.0,cash on delivery,Birmingham,United Kingdom,Delivered,3.0,2025-10-16
4,ORD000740,CUST00349,06 Apr 2026,Home & Kitchen,Non-Stick Pan,2,72.00,0.0,credit card,Montreal,Canada,Delivered,NaN,2026-04-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175,ORD002515,CUST00071,2025-10-17,Home & Kitchen,Storage Organizer,1,106.25,0.0,net banking,Chicago,United States,Delivered,4.0,2025-10-17
12176,ORD011799,CUST02583,2024/01/22,Beauty,Sunscreen SPF50,1,24.76,15.0,paypal,Mumbai,India,Delivered,5.0,2024-01-22
12177,ORD006638,CUST02113,02-28-2024,Grocery,Olive Oil 1L,1,29.95,10.0,upi,Melbourne,Australia,Pending,NaN,2024-02-28
12178,ORD002576,CUST00298,2025-06-01,Beauty,Hair Dryer,1,41.41,15.0,credit card,Vancouver,Canada,Delivered,NaN,2025-06-01
12179,ORD007337,CUST00195,11-18-2024,Books,Self-Help Book,4,27.81,0.0,net banking,Mumbai,India,Delivered,4.0,2024-11-18

In [26]:
df['Country'].isna().sum()

np.int64(19)

In [27]:
df['Country'].unique()

<StringArray>
[      'United Kingdom',               'Canada',            'Australia',
        'United States',              'Germany',                'India',
 'United Arab Emirates',                    nan]
Length: 8, dtype: str

In [28]:
df['Country']=df['Country'].fillna("Unknown")

In [29]:
df['Country'].isna().sum()

np.int64(0)

In [30]:
df['Shipping_City'].isna().sum()

np.int64(502)

In [31]:
df['Shipping_City'] = df['Shipping_City'].fillna("Unknown")

In [32]:
df.head(20)

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating,create_order_date
0,ORD011416,CUST00003,2026-04-03,Books,Self-Help Book,3,9.16,5.0,net banking,London,United Kingdom,Delivered,5.0,2026-04-03
1,ORD000974,CUST00269,10-15-2024,Books,Fiction Novel,1,34.24,5.0,net banking,Toronto,Canada,Shipped,NaN,2024-10-15
2,ORD000617,CUST02075,17 Jun 2024,Home & Kitchen,Vacuum Cleaner,2,111.95,15.0,debit card,Brisbane,Australia,Shipped,NaN,2024-06-17
3,ORD006437,CUST02109,16/10/2025,Beauty,Hair Dryer,1,31.84,0.0,cash on delivery,Birmingham,United Kingdom,Delivered,3.0,2025-10-16
4,ORD000740,CUST00349,06 Apr 2026,Home & Kitchen,Non-Stick Pan,2,72.00,0.0,credit card,Montreal,Canada,Delivered,NaN,2026-04-06
5,ORD011216,CUST02900,11-09-2024,Home & Kitchen,Storage Organizer,1,125.28,0.0,net banking,Los Angeles,United States,Delivered,4.0,2024-11-09
6,ORD002861,CUST01324,21/03/2026,Fashion,Formal Shirt,1,18.34,5.0,upi,Brisbane,Australia,Cancelled,NaN,2026-03-21
7,ORD011407,CUST00135,10/07/2024,Books,Cookbook,3,37.49,0.0,cash on delivery,New York,United States,Returned,NaN,2024-10-07
8,ORD005427,CUST00945,19/08/2025,Home & Kitchen,Vacuum Cleaner,4,21.44,0.0,net banking,Los Angeles,United States,Shipped,NaN,2025-08-19
9,ORD002304,CUST02603,07-14-2025,Sports,Dumbbell Set,1,20.77,10.0,paypal,Munich,Germany,Cancelled,NaN,2025-07-14
10,ORD006172,CUST00940,06-05-2024,Books,Kids Storybook,3,37.22,5.0,debit card,Melbourne,Australia,Delivered,NaN,2024-06-05
11,ORD001560,CUST02535,09 Jun 2025,Beauty,Sunscreen SPF50,2,30.41,10.0,paypal,Montreal,Canada,Delivered,5.0,2025-06-09
12,ORD006143,CUST01216,11 Jun 2025,Toys,Remote Control Car,2,50.78,0.0,credit card,Manchester,United Kingdom,Shipped,NaN,2025-06-11
13,ORD002406,CUST00026,12-09-2024,Toys,Action Figure,1,14.44,0.0,cash on delivery,Montreal,Canada,Shipped,NaN,2024-12-09
14,ORD008099,CUST00959,12-23-2025,Sports,Cycling Helmet,1,96.33,0.0,credit card,Chicago,United States,Delivered,5.0,2025-12-23
15,ORD000325,CUST02081,15 Jul 2025,Electronics,Webcam,1,121.61,0.0,credit card,Delhi,India,Cancelled,NaN,2025-07-15
16,ORD004378,CUST00157,2025/11/05,Books,Kids Storybook,2,9.06,10.0,debit card,Houston,United States,Delivered,4.0,2025-11-05
17,ORD006544,CUST01974,11 Nov 2025,Fashion,Cotton T-Shirt,2,27.82,20.0,net banking,Hamburg,Germany,Delivered,4.0,2025-11-11
18,ORD011722,CUST00989,04/04/2025,Toys,Building Blocks Set,5,78.21,15.0,cash on delivery,Toronto,Canada,Delivered,5.0,2025-04-04
19,ORD011697,CUST02152,04-16-2026,Fashion,Cotton T-Shirt,3,86.68,0.0,paypal,Munich,Germany,Shipped,NaN,2026-04-16

In [33]:
df['Customer_Rating'] = df['Customer_Rating'].fillna("Not Rated")

In [34]:
df["Customer_Rating"].isna().sum()

np.int64(0)

In [35]:
df

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating,create_order_date
0,ORD011416,CUST00003,2026-04-03,Books,Self-Help Book,3,9.16,5.0,net banking,London,United Kingdom,Delivered,5.0,2026-04-03
1,ORD000974,CUST00269,10-15-2024,Books,Fiction Novel,1,34.24,5.0,net banking,Toronto,Canada,Shipped,Not Rated,2024-10-15
2,ORD000617,CUST02075,17 Jun 2024,Home & Kitchen,Vacuum Cleaner,2,111.95,15.0,debit card,Brisbane,Australia,Shipped,Not Rated,2024-06-17
3,ORD006437,CUST02109,16/10/2025,Beauty,Hair Dryer,1,31.84,0.0,cash on delivery,Birmingham,United Kingdom,Delivered,3.0,2025-10-16
4,ORD000740,CUST00349,06 Apr 2026,Home & Kitchen,Non-Stick Pan,2,72.00,0.0,credit card,Montreal,Canada,Delivered,Not Rated,2026-04-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175,ORD002515,CUST00071,2025-10-17,Home & Kitchen,Storage Organizer,1,106.25,0.0,net banking,Chicago,United States,Delivered,4.0,2025-10-17
12176,ORD011799,CUST02583,2024/01/22,Beauty,Sunscreen SPF50,1,24.76,15.0,paypal,Mumbai,India,Delivered,5.0,2024-01-22
12177,ORD006638,CUST02113,02-28-2024,Grocery,Olive Oil 1L,1,29.95,10.0,upi,Melbourne,Australia,Pending,Not Rated,2024-02-28
12178,ORD002576,CUST00298,2025-06-01,Beauty,Hair Dryer,1,41.41,15.0,credit card,Vancouver,Canada,Delivered,Not Rated,2025-06-01
12179,ORD007337,CUST00195,11-18-2024,Books,Self-Help Book,4,27.81,0.0,net banking,Mumbai,India,Delivered,4.0,2024-11-18

In [36]:
df['Order_Date'] = df['create_order_date']

In [37]:
df.drop(columns="create_order_date" ,axis="1",inplace=True)

In [38]:
df

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating
0,ORD011416,CUST00003,2026-04-03,Books,Self-Help Book,3,9.16,5.0,net banking,London,United Kingdom,Delivered,5.0
1,ORD000974,CUST00269,2024-10-15,Books,Fiction Novel,1,34.24,5.0,net banking,Toronto,Canada,Shipped,Not Rated
2,ORD000617,CUST02075,2024-06-17,Home & Kitchen,Vacuum Cleaner,2,111.95,15.0,debit card,Brisbane,Australia,Shipped,Not Rated
3,ORD006437,CUST02109,2025-10-16,Beauty,Hair Dryer,1,31.84,0.0,cash on delivery,Birmingham,United Kingdom,Delivered,3.0
4,ORD000740,CUST00349,2026-04-06,Home & Kitchen,Non-Stick Pan,2,72.00,0.0,credit card,Montreal,Canada,Delivered,Not Rated
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175,ORD002515,CUST00071,2025-10-17,Home & Kitchen,Storage Organizer,1,106.25,0.0,net banking,Chicago,United States,Delivered,4.0
12176,ORD011799,CUST02583,2024-01-22,Beauty,Sunscreen SPF50,1,24.76,15.0,paypal,Mumbai,India,Delivered,5.0
12177,ORD006638,CUST02113,2024-02-28,Grocery,Olive Oil 1L,1,29.95,10.0,upi,Melbourne,Australia,Pending,Not Rated
12178,ORD002576,CUST00298,2025-06-01,Beauty,Hair Dryer,1,41.41,15.0,credit card,Vancouver,Canada,Delivered,Not Rated
12179,ORD007337,CUST00195,2024-11-18,Books,Self-Help Book,4,27.81,0.0,net banking,Mumbai,India,Delivered,4.0

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          12180 non-null  str
 1   Customer_ID       12180 non-null  str
 2   Order_Date        12180 non-null  datetime64[us]
 3   Product_Category  12180 non-null  str
 4   Product_Name      12180 non-null  str
 5   Quantity          12180 non-null  int64
 6   Unit_Price_USD    12180 non-null  float64
 7   Discount_Percent  12180 non-null  float64
 8   Payment_Method    12180 non-null  str
 9   Shipping_City     12180 non-null  str
 10  Country           12180 non-null  str
 11  Order_Status      12180 non-null  str
 12  Customer_Rating   12180 non-null  object
dtypes: datetime64[us](1), float64(2), int64(1), object(1), str(8)
memory usage: 1.2+ MB

In [40]:
df.describe()

,Order_Date,Quantity,Unit_Price_USD,Discount_Percent
count,12180,12180.000000,12180.00000,12180.000000
mean,2025-04-02 00:27:18.620689,2.019458,61.55069,6.858785
min,2024-01-01 00:00:00,-1.000000,3.01000,0.000000
25%,2024-08-13 00:00:00,1.000000,22.02000,0.000000
50%,2025-04-04 00:00:00,2.000000,42.76500,5.000000
75%,2025-11-13 00:00:00,3.000000,87.71250,10.000000
max,2026-12-06 00:00:00,5.000000,249.84000,25.000000
std,NaN,1.234956,52.53839,7.117463

In [41]:
df[df['Quantity']<0]

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating
197,ORD006541,CUST02024,2024-08-11,Fashion,Running Shoes,-1,79.88,15.0,credit card,Montreal,Canada,Returned,Not Rated
285,ORD000653,CUST03243,2024-11-28,Fashion,Sunglasses,-1,83.03,0.0,paypal,Brisbane,Australia,Delivered,4.0
378,ORD010769,CUST00449,2025-03-07,Electronics,Smartwatch,-1,186.96,20.0,debit card,London,United Kingdom,Delivered,4.0
396,ORD004691,CUST00070,2024-07-28,Home & Kitchen,Storage Organizer,-1,144.25,10.0,net banking,Berlin,Germany,Pending,Not Rated
421,ORD011689,CUST01946,2024-05-13,Home & Kitchen,LED Desk Lamp,-1,17.59,20.0,credit card,Bengaluru,India,Delivered,Not Rated
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11273,ORD006663,CUST02468,2024-10-05,Books,Cookbook,-1,23.62,0.0,paypal,Delhi,India,Delivered,4.0
11476,ORD009771,CUST02387,2024-03-03,Fashion,Denim Jacket,-1,48.49,5.0,debit card,Melbourne,Australia,Shipped,Not Rated
11482,ORD005630,CUST02716,2024-04-08,Electronics,Power Bank,-1,39.62,15.0,cash on delivery,Montreal,Canada,Cancelled,Not Rated
11819,ORD007397,CUST00764,2024-04-30,Beauty,Shampoo,-1,24.49,10.0,cash on delivery,Mumbai,India,Pending,Not Rated
11990,ORD006503,CUST02234,2024-10-11,Toys,Building Blocks Set,-1,55.90,5.0,paypal,Los Angeles,United States,Delivered,3.0

In [42]:
df = df.drop_duplicates()

In [43]:
df.duplicated().sum()

np.int64(0)

In [44]:
df[df["Quantity"]<=0][['Quantity','Order_Status','Payment_Method']]

       Quantity Order_Status    Payment_Method
197          -1     Returned       credit card
265           0    Delivered               upi
285          -1    Delivered            paypal
339           0    Delivered       net banking
378          -1    Delivered        debit card
...         ...          ...               ...
11819        -1      Pending  cash on delivery
11905         0      Shipped       net banking
11965         0    Delivered            paypal
11990        -1    Delivered            paypal
12095         0    Delivered  cash on delivery

[186 rows x 3 columns]

In [45]:
df.loc[df['Quantity']<=0,"Quantity"] = np.nan

In [46]:
df[df['Quantity']<=0]

Empty DataFrame
Columns: [Order_ID, Customer_ID, Order_Date, Product_Category, Product_Name, Quantity, Unit_Price_USD, Discount_Percent, Payment_Method, Shipping_City, Country, Order_Status, Customer_Rating]
Index: []

In [47]:
df.info()

<class 'pandas.DataFrame'>
Index: 12000 entries, 0 to 12179
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          12000 non-null  str
 1   Customer_ID       12000 non-null  str
 2   Order_Date        12000 non-null  datetime64[us]
 3   Product_Category  12000 non-null  str
 4   Product_Name      12000 non-null  str
 5   Quantity          11814 non-null  float64
 6   Unit_Price_USD    12000 non-null  float64
 7   Discount_Percent  12000 non-null  float64
 8   Payment_Method    12000 non-null  str
 9   Shipping_City     12000 non-null  str
 10  Country           12000 non-null  str
 11  Order_Status      12000 non-null  str
 12  Customer_Rating   12000 non-null  object
dtypes: datetime64[us](1), float64(3), object(1), str(8)
memory usage: 1.3+ MB

In [48]:
df.describe()

,Order_Date,Quantity,Unit_Price_USD,Discount_Percent
count,12000,11814.000000,12000.000000,12000.000000
mean,2025-04-01 23:41:52.800000,2.058659,61.524733,6.870833
min,2024-01-01 00:00:00,1.000000,3.010000,0.000000
25%,2024-08-13 00:00:00,1.000000,22.020000,0.000000
50%,2025-04-04 00:00:00,2.000000,42.780000,5.000000
75%,2025-11-13 00:00:00,3.000000,87.712500,10.000000
max,2026-12-06 00:00:00,5.000000,249.840000,25.000000
std,NaN,1.199634,52.457089,7.121566

In [49]:
df['Order_Date'].isna().sum()

np.int64(0)

In [50]:
df['Quantity'].isna().sum()

np.int64(186)

In [51]:
df

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating
0,ORD011416,CUST00003,2026-04-03,Books,Self-Help Book,3.0,9.16,5.0,net banking,London,United Kingdom,Delivered,5.0
1,ORD000974,CUST00269,2024-10-15,Books,Fiction Novel,1.0,34.24,5.0,net banking,Toronto,Canada,Shipped,Not Rated
2,ORD000617,CUST02075,2024-06-17,Home & Kitchen,Vacuum Cleaner,2.0,111.95,15.0,debit card,Brisbane,Australia,Shipped,Not Rated
3,ORD006437,CUST02109,2025-10-16,Beauty,Hair Dryer,1.0,31.84,0.0,cash on delivery,Birmingham,United Kingdom,Delivered,3.0
4,ORD000740,CUST00349,2026-04-06,Home & Kitchen,Non-Stick Pan,2.0,72.00,0.0,credit card,Montreal,Canada,Delivered,Not Rated
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175,ORD002515,CUST00071,2025-10-17,Home & Kitchen,Storage Organizer,1.0,106.25,0.0,net banking,Chicago,United States,Delivered,4.0
12176,ORD011799,CUST02583,2024-01-22,Beauty,Sunscreen SPF50,1.0,24.76,15.0,paypal,Mumbai,India,Delivered,5.0
12177,ORD006638,CUST02113,2024-02-28,Grocery,Olive Oil 1L,1.0,29.95,10.0,upi,Melbourne,Australia,Pending,Not Rated
12178,ORD002576,CUST00298,2025-06-01,Beauty,Hair Dryer,1.0,41.41,15.0,credit card,Vancouver,Canada,Delivered,Not Rated
12179,ORD007337,CUST00195,2024-11-18,Books,Self-Help Book,4.0,27.81,0.0,net banking,Mumbai,India,Delivered,4.0

In [52]:
df.shape

(12000, 13)

In [53]:
df.isna().sum()

Order_ID              0
Customer_ID           0
Order_Date            0
Product_Category      0
Product_Name          0
Quantity            186
Unit_Price_USD        0
Discount_Percent      0
Payment_Method        0
Shipping_City         0
Country               0
Order_Status          0
Customer_Rating       0
dtype: int64

In [54]:
df.duplicated().sum()

np.int64(0)

In [55]:
df.dtypes

Order_ID                       str
Customer_ID                    str
Order_Date          datetime64[us]
Product_Category               str
Product_Name                   str
Quantity                   float64
Unit_Price_USD             float64
Discount_Percent           float64
Payment_Method                 str
Shipping_City                  str
Country                        str
Order_Status                   str
Customer_Rating             object
dtype: object

In [56]:
(df['Quantity']<=0).sum()

np.int64(0)

In [70]:
df['Total_Amount'] = (df['Unit_Price_USD']*df['Quantity']* (1-df['Discount_Percent']/100)).round(2)
df["Total_Amount"].head(10)

0     26.11
1     32.53
2    190.32
3     31.84
4    144.00
5    125.28
6     17.42
7    112.47
8     85.76
9     18.69
Name: Total_Amount, dtype: float64

In [71]:
df['Total_Amount'].isna().sum()

np.int64(186)

In [72]:
print(df[['Quantity','Unit_Price_USD','Discount_Percent',"Total_Amount"]].dtypes)

Quantity            float64
Unit_Price_USD      float64
Discount_Percent    float64
Total_Amount        float64
dtype: object

In [73]:
df.to_csv("ecom.cleaned.csv",index=False)

In [74]:
df.dtypes

Order_ID                       str
Customer_ID                    str
Order_Date          datetime64[us]
Product_Category               str
Product_Name                   str
Quantity                   float64
Unit_Price_USD             float64
Discount_Percent           float64
Payment_Method                 str
Shipping_City                  str
Country                        str
Order_Status                   str
Customer_Rating             object
Total_Amount               float64
dtype: object

df['Order_Id'].unique()

In [77]:
df['Order_ID'].nunique()

12000

In [78]:
df.shape[0]

12000

In [79]:
## connecting to MYSQL

In [80]:
import mysql.connector

In [ ]:
conn = mysql.connector.connect(
  host = "localhost",
  user = "root",
  password = "PASS",
  database = "ecommerce_de"
)

In [82]:
conn.is_connected()

True

In [83]:
cursor = conn.cursor()

In [84]:
row = df.iloc[0]
print(row)

Order_ID                      ORD011416
Customer_ID                   CUST00003
Order_Date          2026-04-03 00:00:00
Product_Category                  Books
Product_Name             Self-Help Book
Quantity                            3.0
Unit_Price_USD                     9.16
Discount_Percent                    5.0
Payment_Method              net banking
Shipping_City                    London
Country                  United Kingdom
Order_Status                  Delivered
Customer_Rating                     5.0
Total_Amount                      26.11
Name: 0, dtype: object

In [85]:
values = tuple(df.iloc[0])
print(values)

('ORD011416', 'CUST00003', Timestamp('2026-04-03 00:00:00'), 'Books', 'Self-Help Book', np.float64(3.0), np.float64(9.16), np.float64(5.0), 'net banking', 'London', 'United Kingdom', 'Delivered', 5.0, np.float64(26.11))

In [86]:
query = """
INSERT INTO ecommerce_transactions
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

In [87]:
cursor.execute(query,values)
conn.commit()

In [93]:
df = df.astype(object).where(df.notna(), None)

In [94]:
print(df["Quantity"].isna().sum())
print(df["Quantity"].iloc[0])

186
3.0

In [95]:
print([x for x in df["Quantity"] if x is None][:5])

[None, None, None, None, None]

In [96]:
values = [
    tuple(row)
    for row in df.iloc[1:].itertuples(index=False, name=None)
]

In [97]:
cursor.executemany(query,values)
conn.commit()

In [98]:
print(len(df))

12000